fix and add more functions

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -11,88 +11,84 @@
 
 source ~/.config/shell/aliases
 
-# Show available prompt colors for default Linux bash
-colorsinfo () {
-	local fgc bgc vals seq0
+function porcmem () {
+	local column=$(free -w | egrep "Mem:")
+	local porc=$(( $(echo $column | awk '{print $3}') * 100 ))
+	porc=$(( $porc / $(echo $column | awk '{print $2}') ))
 
-	# foreground colors
-	for fgc in {30..37}; do
-		# background colors
-		for bgc in {40..47}; do
-			fgc=${fgc#37} # white
-			bgc=${bgc#40} # black
-
-			vals="${fgc:+$fgc;}${bgc}"
-			vals=${vals%%;}
-
-			seq0="${vals:+\e[${vals}m}"
-			printf "  %-9s" "${seq0:-(default)}"
-			printf " ${seq0}TEXT\e[m"
-			printf " \e[${vals:+${vals+$vals;}}1mBOLD\e[m"
-			echo
-		done
-
-		echo; echo
-	done
+	return $porc
 }
 
 # Show current RAM status in human-readable output
-raminfo () {
-	# Obtain porcentage usage in bytes
-	local porc=$(($(free -w | grep "Mem:" | awk '{print $3}')*100))
-	porc=$(($porc/$(free -w | grep "Mem:" | awk '{print $2}')))
+function raminfo () {
+	local porc=$(porcmem; echo $?)
 
-	# Format used and total in human-readable output
-	local used=$(free -hw | grep "Mem:" | awk '{print $3}')
-	local total=$(free -hw | grep "Mem:" | awk '{print $2}')
+	local column=$(free -hw | grep "Mem:")
+	local used=$(echo $column | awk '{print $3}')
+	local total=$(echo $column | awk '{print $2}')
 
 	echo "${used} / ${total} (${porc}%)"
-	unset used total porc
 }
 
 # Show some information about a target specified in param $1
 # # usage: mountinfo /home
-mountinfo () {
+function mountinfo () {
 	if [[ -z $1 ]]; then
-		echo "ERROR!! Target not specified"
+		echo "error: mountinfo: target not specified" 1>&2
+		echo "use: mountinfo: mountinfo <TARGET>" 1>&2
+		return 1
 	else
-		touch /temp/temp.txt
+		tempfile=$(mktemp)
 
 		# Find and store in a file what are the candidates
-		df -h --output=used,size,pcent,fstype,target | grep "$1" > /temp/temp.txt
+		df -h --output=used,size,pcent,fstype,target | grep "$1" > $tempfile
 
 		# Check if target exists in current file system
 		while IFS= read -r line; do
 				if [[ $(echo $line | awk '{print $5}') = $1 ]]; then
-					local used=$(echo $line | awk '{print $1}')
-					local size=$(echo $line | awk '{print $2}')
-					local pcent=$(echo $line | awk '{print $3}')
-					local fstype=$(echo $line | awk '{print $4}')
-
-					echo "$used | $size ($pcent) ($fstype)"
-					unset used size pcent fstype
-
-					rm /temp/temp.txt
+					echo $line | awk '{print $1 " | " $2 " (" $3 ")" " (" $4 ")"}'
 					return 0
 				fi
-		done < /temp/temp.txt
+		done < $tempfile
 
-		echo "Unkown target"
-		rm /temp/temp.txt
+		echo "error: mountinfo: unkown target" 1>&2
+		echo "use: mountinfo: mountinfo <TARGET>" 1>&2
+		return 1
+	fi
+}
+
+# Create several sh files at current path
+# # usage: mksh <SH_FILE1> <SH_FILE2> ...
+function mksh () {
+	if (( $# >= 1 )); then
+		while (( $# != 0 )); do
+			if [[ $1 =~ .+\.sh ]]; then
+				touch $1
+				chmod +x $1
+			else
+				echo "error: mksh: file needs to be a .sh file" 1>&2
+				echo "use: mksh: mksh <SH_FILE1> <SH_FILE2> ..." 1>&2
+			fi
+
+			shift
+		done
+	else
+		echo "error: mksh: invalid number of arguments" 1>&2
+		echo "use: mksh: mksh <SH_FILE1> <SH_FILE2> ..." 1>&2
+		return 1
 	fi
 
-	return -1
 }
 
 # Create a new directory and enter it
 # # usage: mkd <directory_path>
-mkd () {
+function mkd () {
 	mkdir -p "$@" && cd "$_"
 }
 
 # Remove all files inside a folder
 # # usage: rmmkdir <folder_path>
-rmmkdir () {
+function rmmkdir () {
 	if [[ -f $1 ]]; then
 		rm -R $1 &>/dev/null
 		mkdir -R $1 &>/dev/null
@@ -105,31 +101,23 @@ rmmkdir () {
 
 # Determine size of a file or total size of a directory
 # # usage: fs <directory/file>
-fs () {
-	local arg=-sh
-
-	if du -b /dev/null > /dev/null 2>&1; then
-		arg=-sbh
-	fi
-
+function fs () {
 	if [[ -n "$@" ]]; then
-		du $arg -- "$@"
+		du -sh -- "$@"
 	else
-		du $arg .[^.]* ./*
+		du -sh ./*
 	fi
-
-	unset arg
 }
 
 # # ex - archive extractor
 # Extracts current file according its format
 # # usage: ex <file>
-ex () {
-  if [ -f $1 ] ; then
-    case $1 in
+function ex () {
+  if [[ -f $1 ]] ; then
+  	case $1 in
       *.tar.bz2)   tar xjf $1   ;;
       *.tar.gz)    tar xzf $1   ;;
-			*.tar.xz)		 tar xf $1		;;
+	  *.tar.xz)		 tar xf $1	;;
       *.bz2)       bunzip2 $1   ;;
       *.rar)       unrar x $1   ;;
       *.gz)        gunzip $1    ;;
